---
Name: innoweb-enhancedrss
---
SilverStripe\Control\RSS\RSSFeed_Entry:
  extensions:
    - Innoweb\EnhancedRSS\Extensions\RSSFeedEntryExtension

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Innoweb\EnhancedRSS\Extensions\RSSFeedSiteTreeExtension
